### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by webwnet** [harishdurga/laravel-video-chat#2]
How to install  I just want to use it in the browser.

**Comment by harishdurga** [comment]
1. Clone the repo
2. Install the dependencies running composer install
3. Modify the credentials in .env for Database
4. Follow the instruction at https://beyondco.de/docs/laravel-websockets/getting-started/introduction to run the websocket server which will be used for sending text message and signalling
5. Get a twillio account using www.twilio.com/referral/cxgjIQ which is being used for Video Calling. After creating an account in Twillio setup these variable in your .env file 
TWILLIO_ACCOUNT_ID=
TWILLIO_AUTH_TOKEN= 
TWILIO_ACCOUNT_SID = 
TWILIO_API_KEY_SID = 
TWILIO_API_KEY_SECRET = 
6. For chat translation to work you need a google translate project. After setting that up, set GOOGLE_APPLICATION_CREDENTIALS='path to service account json file'
GOOGLE_PROJECT_ID="project-id"
